# .github/workflows/test.yml
name: tests

on:
  push:
  pull_request:

jobs:
  bats:
    runs-on: ubuntu-latest
    env:
      SKIP_ROOT_CHECK: "1"
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Ensure executable bits
        run: chmod +x bin/usb-wakeup-blocker.sh test/run-tests.sh

      - name: Init submodules (recursive)
        run: git submodule update --init --recursive

      - name: Install kcov
        run: sudo apt-get install kcov

      - name: Run Bats tests with kcov
        run: kcov test_coverage_output ./test/run-tests.sh > test_output.log 2>&1
        continue-on-error: true

      - name: Upload kcov coverage report
        uses: actions/upload-artifact@v4
        with:
          name: kcov-report
          path: test_coverage_output

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test_output.log

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck
