# .github/workflows/test.yml
name: tests

on:
  push:
  pull_request:

jobs:
  bats:
    runs-on: ubuntu-latest
    env:
      SKIP_ROOT_CHECK: "1"
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Ensure executable bits
        run: chmod +x bin/usb-wakeup-blocker.sh test/run-tests.sh

      - name: Init submodules (recursive)
        run: git submodule update --init --recursive

      - name: Run Bats tests (no sudo)
        run: ./test/run-tests.sh

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck
