# .github/workflows/test.yml
name: test
on: [push, pull_request]

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true   # ←これが肝
      - name: Run tests
        run: sudo ./test/run-tests.sh