# .github/workflows/test.yml
name: tests

on:
  push:
  pull_request:

jobs:
  bats:
    runs-on: ubuntu-latest
    env:
      # テストでroot不要にする（スクリプト側でこの環境変数を見てrequire_rootをスキップ）
      SKIP_ROOT_CHECK: "1"
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      # 念のため実行属性を付与（既に付いていても無害）
      - name: Ensure executable bits
        run: chmod +x bin/usb-wakeup-blocker.sh test/run-tests.sh

      # まれに必要になることがあるので保険として
      - name: Init submodules (recursive)
        run: git submodule update --init --recursive

      - name: Run Bats tests (no sudo)
        run: ./test/run-tests.sh